spring.application.name=meupet

spring.jpa.properties.hibernate.format_sql=true

meupet.security.secret-key=${MEUPET_SECRET_KEY}
meupet.security.salt=${MEUPET_SALT}
meupet.security.jwt-expiration-ms=86400000

spring.jpa.defer-datasource-initialization=true