spring.application.name=meupet

spring.datasource.driver-class-name=org.h2.Driver

spring.datasource.username=sa
spring.datasource.password=
spring.datasource.url=jdbc:h2:mem:db
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

spring.jpa.hibernate.ddl-auto=update

meupet.security.secret-key=${MEUPET_SECRET_KEY:chave-temporaria-para-dev}
meupet.security.salt=${MEUPET_SALT:a1b2c3d4e5f60708}
# pra quando a gnt for usar .env pra mexer com esse bo da criptografia...
# por enquanto vamo usar essa chave temporaria ali em cima!
# meupet.security.secret-key=${MEUPET_SECRET_KEY}
# meupet.security.salt=${MEUPET_SALT}

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.h2.console.enabled=true
spring.h2.console.path=/h2